import type { Product } from '@/types';

export const categories = ['Whiskey', 'Gin', 'Vodka', 'Rum', 'Tequila'] as const;

export const products: Product[] = [
  {
    id: '1',
    name: 'Emberfall Bourbon',
    category: 'Whiskey',
    price: 59.99,
    image: 'https://placehold.co/600x600',
    description: 'A rich, smooth bourbon with notes of caramel, vanilla, and a hint of oak smoke. Aged for 12 years in charred oak barrels for exceptional depth.',
    details: ['Type: Bourbon', 'ABV: 45%', 'Origin: Kentucky, USA'],
    featured: true,
    recipe: {
      name: 'Emberfall Old Fashioned',
      ingredients: ['60ml Emberfall Bourbon', '1 Sugar Cube', '2 Dashes Angostura Bitters', 'Orange Peel'],
      instructions: ['Muddle sugar cube and bitters in a glass.', 'Add bourbon and a large ice cube.', 'Stir until chilled.', 'Garnish with an orange peel.'],
    },
  },
  {
    id: '2',
    name: 'Juniper-Mist Gin',
    category: 'Gin',
    price: 45.99,
    image: 'https://placehold.co/600x600',
    description: 'A classic London Dry Gin, distilled with a secret blend of botanicals including juniper, coriander, and citrus peel for a crisp, refreshing taste.',
    details: ['Type: London Dry Gin', 'ABV: 47%', 'Origin: London, UK'],
    featured: true,
    recipe: {
      name: 'Juniper-Mist & Tonic',
      ingredients: ['50ml Juniper-Mist Gin', '150ml Premium Tonic Water', 'Lime Wedge'],
      instructions: ['Fill a highball glass with ice.', 'Pour in the gin and top with tonic water.', 'Squeeze and drop in a lime wedge to garnish.'],
    },
  },
  {
    id: '3',
    name: 'Crystal Peak Vodka',
    category: 'Vodka',
    price: 39.99,
    image: 'https://placehold.co/600x600',
    description: 'An exceptionally smooth vodka, filtered through quartz crystals for unparalleled purity. Clean, crisp, with a subtly sweet finish.',
    details: ['Type: Grain Vodka', 'ABV: 40%', 'Origin: Poland'],
    featured: false,
    recipe: {
      name: 'Crystal Peak Moscow Mule',
      ingredients: ['50ml Crystal Peak Vodka', '100ml Ginger Beer', '10ml Lime Juice'],
      instructions: ['Fill a copper mug with ice.', 'Add vodka and lime juice.', 'Top with ginger beer and stir gently.', 'Garnish with a lime wheel.'],
    },
  },
  {
    id: '4',
    name: 'Golden Isles Rum',
    category: 'Rum',
    price: 52.50,
    image: 'https://placehold.co/600x600',
    description: 'A dark aged rum from the Caribbean, boasting complex flavors of molasses, tropical fruit, and spice. Perfect for sipping or in a classic cocktail.',
    details: ['Type: Dark Rum', 'ABV: 43%', 'Origin: Barbados'],
    featured: true,
    recipe: {
      name: 'Golden Isles Mai Tai',
      ingredients: ['60ml Golden Isles Rum', '15ml Orange Curaçao', '15ml Orgeat Syrup', '30ml Lime Juice'],
      instructions: ['Shake all ingredients with ice.', 'Strain into a glass filled with crushed ice.', 'Garnish with a mint sprig and lime peel.'],
    },
  },
  {
    id: '5',
    name: 'Sol Agave Tequila',
    category: 'Tequila',
    price: 65.00,
    image: 'https://placehold.co/600x600',
    description: 'A premium 100% blue agave tequila, rested in oak barrels for a smooth, complex flavor with notes of cooked agave, vanilla, and caramel.',
    details: ['Type: Tequila Reposado', 'ABV: 40%', 'Origin: Jalisco, Mexico'],
    featured: false,
    recipe: {
      name: 'Sol Agave Margarita',
      ingredients: ['50ml Sol Agave Tequila', '25ml Cointreau', '25ml Fresh Lime Juice', 'Salt for rim'],
      instructions: ['Rim a chilled glass with salt.', 'Shake tequila, Cointreau, and lime juice with ice.', 'Strain into the prepared glass.'],
    },
  },
   {
    id: '6',
    name: 'Highland Peat Scotch',
    category: 'Whiskey',
    price: 89.99,
    image: 'https://placehold.co/600x600',
    description: 'A smoky and peaty single malt Scotch from the Islay region. Intense flavors of campfire smoke, sea salt, and a lingering spice.',
    details: ['Type: Single Malt Scotch', 'ABV: 46%', 'Origin: Islay, Scotland'],
    recipe: {
      name: 'The Peat Neat',
      ingredients: ['50ml Highland Peat Scotch', '1 drop of water (optional)'],
      instructions: ['Pour the Scotch into a Glencairn glass.', 'Add a drop of still water to open up the aromas, if desired.', 'Sip slowly and savor.'],
    },
  },
  {
    id: '7',
    name: 'Botanical Garden Gin',
    category: 'Gin',
    price: 48.99,
    image: 'https://placehold.co/600x600',
    description: 'A floral and herbaceous gin infused with rose petals, chamomile, and elderflower. Light, delicate, and perfect for spring cocktails.',
    details: ['Type: Floral Gin', 'ABV: 42%', 'Origin: England'],
    recipe: {
      name: 'Garden Party Spritz',
      ingredients: ['50ml Botanical Garden Gin', '25ml Elderflower Liqueur', '100ml Prosecco', 'Cucumber Ribbon'],
      instructions: ['Build in a large wine glass filled with ice.', 'Stir gently.', 'Garnish with a ribbon of cucumber.'],
    },
  },
  {
    id: '8',
    name: 'Spiced Molasses Rum',
    category: 'Rum',
    price: 49.99,
    image: 'https://placehold.co/600x600',
    description: 'A rich and bold spiced rum with dominant notes of cinnamon, nutmeg, and vanilla, balanced with a deep molasses sweetness.',
    details: ['Type: Spiced Rum', 'ABV: 40%', 'Origin: Jamaica'],
    recipe: {
      name: 'Spiced & Stormy',
      ingredients: ['50ml Spiced Molasses Rum', '150ml Ginger Beer', 'Lime Wedge'],
      instructions: ['Fill a highball glass with ice.', 'Pour in the rum and top with ginger beer.', 'Squeeze in a wedge of lime and serve.'],
    },
  },
];
